### ISSUE TITLE
Support `name` attribute for entity

### ISSUE THREAD

**Issue by stephanmiehe** [tcarlsen/lovelace-light-with-profiles#3]
It would be great to have the ability to override names of entities just like the entities card that ships with HA. 

```
- entity: light.spisestuen
    name: 'My light'
    profiles:
      - name: bright
        icon: 'mdi:brightness-5'
      - name: dimmed
        icon: 'mdi:brightness-4'
      - name: nightlight
        icon: 'mdi:brightness-3'
```
